Homework 4 mvvm
Voodstr/OtusLesson pull request #4
Opened 2021-05-27 16:46 UTC by Voodstr

Не реализована пагинация и работа с загрузкой изображений (GLIDE). 28.05 сделаю

2021-06-13 13:23 UTC, baidala requested changes
в целом mvvm реализован правильно. fragment - viewmodel- interactor- dataSource. но нужно разделить FilmModel. указать правильные адресса. внести изменения в фрагменты.

2021-06-13 13:23 UTC, baidala commented on .idea/codeStyles/Project.xml
>  <component name="ProjectCodeStyleConfiguration">
все файлы .idea/  лучше добавить в gitignore

2021-06-13 13:23 UTC, baidala commented on app/src/main/java/ru/voodster/otuslesson/App.kt
> +        val okHttpClient = OkHttpClient.Builder()
рекомендовал бы добавить еще  htttpInterceptor  чтоб в дебаге выводить в лог тело запросов
```

implementation "com.squareup.okhttp3:logging-interceptor:4.9.0"
-----------
import okhttp3.logging.HttpLoggingInterceptor
import okhttp3.logging.HttpLoggingInterceptor.Level.BODY
import okhttp3.logging.HttpLoggingInterceptor.Level.NONE

fun provideLoggingInterceptor() =
            HttpLoggingInterceptor().apply { level = if (BuildConfig.DEBUG) BODY else NONE }
*****
val okHttpClient = OkHttpClient.Builder()
            .addInterceptor(provideLoggingInterceptor())
            .build()


```

2021-06-13 13:23 UTC, baidala commented on app/src/main/java/ru/voodster/otuslesson/App.kt
> +        const val BASE_URL = "http://10.0.2.2/"
это какой то локальный адресс? с какого сайтв вы берете данные про фильмы?
`okhttp.OkHttpClient: <-- HTTP FAILED: java.net.SocketTimeoutException: failed to connect to /10.0.2.2 (port 80) from /192.168.50.162 (port 45976) after 10000ms`

2021-06-13 13:23 UTC, baidala commented on app/src/main/java/ru/voodster/otuslesson/about/AboutFragment.kt
> +class AboutFragment(private val film: FilmModel) :Fragment() {
у каждого фрагмента должен быть пустой дефолтный конструктор или при пересоздании/востановлении будут креши. и лучше добавить отдельный метод newInstanse(film: FilmModel) для аргументов. и в onViewCreated доставить эти данные из arguments
```
class AboutFragment :Fragment() {
private lateinit var film: FilmModel
    
    companion object{
        const val TAG = "AboutFragment"
        private const val FILM_DATA = "FILM_DATA"
        fun newInstance(film: FilmModel): AboutFragment {
            val args  = Bundle()
            args.putParcelable(FILM_DATA, film)
            val fragment = AboutFragment()
            fragment.arguments = args
            return fragment
        }
    }
```

2021-06-13 13:23 UTC, baidala commented on app/src/main/java/ru/voodster/otuslesson/about/AboutFragment.kt
> +                .load("http://developer.alexanderklimov.ru/android/images/android_cat.jpg")
в aboutImg нужно  загружать картинку из FilmModel.img.  и рекомендую использовать  .placeholder(**)  и поставить какую то неброскую/однотонную картинку  пока грузится  постер

2021-06-13 13:23 UTC, baidala commented on app/src/main/java/ru/voodster/otuslesson/db/Db.kt
> +                    /*.allowMainThreadQueries()
.allowMainThreadQueries()  - лучше не использовать. сразу приучайтесь что все запросы в сеть/базу  должны иддти в фоне

2021-06-13 13:23 UTC, baidala commented on app/src/main/java/ru/voodster/otuslesson/api/FilmsApi.kt
> +    fun getInitial():Call<List<FilmModel>>
нужно разделить FilmModel - вы можете использовать эту модель в базе данных и на UI уровне (в больших проектах есть модель для базы. модель для rest запросов. и общая модель для UI к которой все сводится). а для сетевых запросов должна быть отдельная модель  для того чтоб эти два источника данных (база и сеть) были максимально независимы друг от друга.  т.к. сейчас - если изменится ответ сервера, вам  нужно переделыыать в двух местах. и при получении данных от сервера вы будете конвертировать в  FilmModel  и сохранять в базу. для этого используется класс -маппер.  пример базового маппера  
https://gist.github.com/baidala/6867528cf6d46a7b10d44370f9cccf27

2021-06-13 13:23 UTC, baidala commented on app/src/main/java/ru/voodster/otuslesson/db/FilmModel.kt
> +class FilmModel {
data class FilmModel  - и для других моделей тоже используйте  data class

2021-06-13 13:42 UTC, baidala commented on app/src/main/java/ru/voodster/otuslesson/about/AboutFragment.kt
> +class AboutFragment(private val film: FilmModel) :Fragment() {
другой вариант записи
return AboutFragment().apply {
                arguments = Bundle().apply {
                    putParcelable(FILM_DATA, film)
                }
            }

2021-06-14 11:34 UTC, Voodstr commented on app/src/main/java/ru/voodster/otuslesson/App.kt
> +        const val BASE_URL = "http://10.0.2.2/"
Свой http сервер запускаю локально. Могу поднять на яндекс облаке в теории

2021-06-17 10:50 UTC, baidala approved these changes
можно мержить с веткой homework5

2021-06-17 10:55 UTC, merged